server:
  port: 8081

spring:
  application:
    name: microservices-kafka-demo

  datasource:
    url: jdbc:mysql://localhost:3306/ms-kafka?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: User123456!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # create, create-drop, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect


  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

      properties:
        spring:
          json:
            add:
              type:
                headers: false
