version: "3.8"

services:

  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"   # UI
      - "14250:14250"   # gRPC interno
    environment:
      - COLLECTOR_OTLP_ENABLED=true

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    restart: unless-stopped
    command:
      - "--config=/etc/otel-config.yaml"
    volumes:
      - ./otel-config.yaml:/etc/otel-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC (apps -> collector)
      - "4318:4318"   # OTLP HTTP
    depends_on:
      - jaeger

#  C:/Users/
#  scp docker-compose.yml german@1.:C:/
#  ssh german@1. "cd C:/Us && docker-compose up -d"