#server:
#  port: 8082
#
#spring:
#  application:
#    name: microservices-kafka-demo-billing
#
#  datasource:
#    url: jdbc:mysql://192.168.0.114:3307/ms-kafka-billing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: user
#    password: User123456!
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#
#  kafka:
#    bootstrap-servers: 192.168.0.114:9092
#
#    producer:
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
#
#      properties:
#        spring:
#          json:
#            add:
#              type:
#                headers: false
#
#
#logging:
#  level:
#    root: INFO
#    io.opentelemetry: DEBUG
#    io.micrometer: DEBUG
#    io.micrometer.tracing: DEBUG
#
#
#
#
#
#management:
#  tracing:
#    enabled: true
#    sampling:
#      probability: 1.0
#
#  otel:
#    service:
#      name: microservices-kafka-demo
#    traces:
#      exporter: otlp
#    metrics:
#      exporter: none
#    exporter:
#      otlp:
#        endpoint: http://192.168.0.114:4317
#        protocol: grpc
#
#
#  endpoints:
#    web:
#      exposure:
#        include: health,info,metrics,prometheus,loggers




server:
  port: 8082

spring:
  application:
    name: microservices-kafka-demo-billing

  datasource:
    url: jdbc:mysql://192.168.0.114:3307/ms-kafka-billing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: user
    password: User123456!
    driver-class-name: com.mysql.cj.jdbc.Driver

  kafka:
    bootstrap-servers: 192.168.0.114:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

logging:
  level:
    root: INFO
    io.opentelemetry: DEBUG
    io.micrometer: DEBUG
    io.micrometer.tracing: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://${JAEGER_HOST:192.168.0.114}:4317
      protocol: grpc