services:
  ms-kafka-consumer:
    container_name: ms-kafka-consumer

    build:
      context: /Users/germanantoniocarrascocalderon/git/ms-kafka-java/ms-java-kafka-demo/microservices-kafka-demo-billing

    image: ms-kafka-consumer:latest

    restart: unless-stopped

    ports:
      - "8082:8082"

    mem_limit: 768m
    cpus: "1.0"

    environment:
      TZ: America/Santo_Domingo
      JAVA_TOOL_OPTIONS: >
        -Dotel.service.name=billing-service
        -Dotel.traces.exporter=otlp
        -Dotel.exporter.otlp.endpoint=http://otel-collector:4317
        -Dotel.exporter.otlp.protocol=grpc
        -Dotel.metrics.exporter=none
        -Dotel.logs.exporter=none

    networks:
      - kafka-network